name: Build html v4.0

on:
  push:
    branches: ["v4.0"]

jobs:
  build:
    runs-on: [self-hosted, ws2]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "v4.0"

      - name: Install requirements.txt
        run: pip install --no-cache -r requirements.txt

      - name: Build html
        run: make html

      - name: Update to web
        run: docker run --rm -v $(pwd)/_build/user/html:/src -v /mnt/web/:/dst:shared ubuntu:22.04 cp -rf /src/. /dst/
